// Generated by LiveScript 1.4.0
(function(){
  var csvCleaner, assert, cleaner;
  csvCleaner = require('../csvCleaner.js');
  assert = require('assert');
  cleaner = new csvCleaner();
  describe('csvCleaner', function(){
    return specify('should remove double quotes in the string', function(){
      var testStr, expectStr, resultStr;
      testStr = 'This is a "test" "string"';
      expectStr = 'This is a test string';
      resultStr = cleaner.removeDoubleQuotesInString(testStr);
      return assert.equal(expectStr, resultStr);
    });
  });
}).call(this);
